---
# tasks file for idracReset
- name: List hosts
  debug:
    var: "{{ hostvars }}"

# - name: FML
#   shell: ansible-galaxy collection list

# - name: iDrac Reset
#   dellemc.openmanage.idrac_reset:
#     idrac_ip: "{{ item }}"
#     idrac_user: "{{ idrac_cred.username }}"
#     idrac_password: "{{ idrac_cred.password }}"
#     validate_certs: false
#   loop: "{{ groups['all'] }}"
#   when: item != "localhost"
#   delegate_to: localhost
