---
# tasks file for ProxmoxRemoveVM
- name: Make sure ServerName is all upper
  set_fact: ServerNameUpper="{{ ServerName | upper }}"
  
- name: Obtain Credentials
  include_role:
    name: GetVaultCreds
  vars:
    includecred:
      - proxmoxroot
      - windowslocaladmin

- name: Shutdown VM
  community.general.proxmox_kvm:
    api_user: "{{ proxmoxroot_cred.username }}"
    api_password: "{{ proxmoxroot_cred.password }}"
    api_host: pmx1.evorigin.com
    name: "{{ ServerNameUpper }}"
    state: stopped
    force: true
  ignore_errors: true

- name: Delete VM
  community.general.proxmox_kvm:
    api_user: "{{ proxmoxroot_cred.username }}"
    api_password: "{{ proxmoxroot_cred.password }}"
    api_host: pmx1.evorigin.com
    name: "{{ ServerNameUpper }}"
    state: absent
    force: true
  ignore_errors: true

- name: Remove VM from Netbox
  include_role:
    name: NetboxRemoveVM
  when: mode == "Decom"