---
# tasks file for NetboxRemoveVM
- name: Obtain netbox api token
  include_role:
    name: GetVaultCreds
  vars:
    includecred:
      - netbox

- name: Make sure ServerName is all upper
  set_fact: ServerNameUpper="{{ ServerName | upper }}"

- name: Create VM
  netbox.netbox.netbox_virtual_machine:
    netbox_url: "{{ netbox_cred.url }}"
    netbox_token: "{{ netbox_cred.token }}"
    data:
      name: "{{ ServerNameUpper }}"
    state: absent
    validate_certs: no
  register: VirtualMachine