---
- name: GetCredentials
  hosts: all
  gather_facts: no
  tasks:
    - name: Obtain Credentials
      include_role:
        name: GetVaultCreds
      vars:
        includecred:
          - windowslocaladmin

- name: Run
  hosts: all
  gather_facts: yes
  vars:
    ansible_user:     "{{ windowslocaladmin_cred.username }}"
    ansible_password: "{{ windowslocaladmin_cred.password }}"
  tasks:
    - name: Run the ConfigureWindows Role
      include_role:
        name: ConfigureWindows