---
- name: GetCredentials
  hosts: all
  gather_facts: no
  tasks:
    - name: Obtain Credentials
      include_role:
        name: GetVaultCreds
      vars:
        includecred:
          - evoriginda
          - zabbixapi

- name: Run
  hosts: all
  gather_facts: yes
  vars:
    ansible_user:     "{{ evoriginda_cred.username }}"
    ansible_password: "{{ evoriginda_cred.password }}"
  tasks:
    - name: Run the ConfigureWindows Role
      include_role:
        name: ConfigureWindows

    - name: Add host to Zabbix
      include_role:
        name: AddToZabbix