---
- name: Generate Private Key and CSR
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Generate Private Key
      community.crypto.openssl_privatekey:
        path: "/tmp/{{ ServerName }}.key"
        size: 2048
      no_log: true

    - name: Generate CSR
      community.crypto.openssl_csr:
        path: "/tmp/{{ ServerName }}.csr"
        privatekey_path: "/tmp/{{ ServerName }}.key"
        country_name: "US"
        state_or_province_name: "FL"
        locality_name: "Jax"
        organization_name: "EvOrigin"
        organizational_unit_name: "Lab"
        email_address: "admin@lab.local"
        common_name: "{{ ServerName }}.evorigin.com"
        key_usage:
          - digitalSignature
          - nonRepudiation
          - keyEncipherment
          - dataEncipherment
        extended_key_usage:
          - serverAuth
          - clientAuth
          - codeSigning
          - emailProtection
        subject_alt_name:
          - "DNS:{{ ServerName }}.evorigin.com"
          # Add more SANs as needed, based on the [alt_names] section
        # return_content: true
      # register: csr
      no_log: true

- name: Create Certificate Using MS CA
  hosts: jax-cert001.evorigin.com
  gather_facts: yes
  tasks:
    - name: Create a folder on Windows Server
      ansible.windows.win_file:
        path: "C:\\CertStuff\\{{ ServerName }}"
        state: directory
  
    - name: Copy CSR to CA Server
      ansible.windows.win_copy:
        src: "/tmp/{{ ServerName }}.csr"
        dest: "C:\\CertStuff\\{{ ServerName }}\\{{ ServerName }}.csr"
        force: true

    - name: Copy Private Key to CA Server
      ansible.windows.win_copy:
        src: "/tmp/{{ ServerName }}.key"
        dest: "C:\\CertStuff\\{{ ServerName }}\\{{ ServerName }}.key"
        force: true