---
- name: Obtain Certificate Authority Info
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Obtain netbox api token
      include_role:
        name: GetVaultCreds
      vars:
        includecred:
          - certificateauthority

- name: Run
  hosts: jax-cert001.evorigin.com
  gather_facts: no
  vars:
    pfx_password: "DeleteMe" #This is not really used but it is required by the CA
    ca_config: "{{ hostvars['localhost']['certificateauthority_info'].ca_config }}"
    cert_template: "{{ hostvars['localhost']['certificateauthority_info'].cert_template }}"
    cert_folder: "C:\\CertStuff\\{{ ServerName }}"
  tasks:
    - name: Run the Role
      include_role:
        name: CreateMsCaCertificate
