---
- name: Generate Private Key and CSR
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Generate Private Key
      community.crypto.openssl_privatekey:
        path: /tmp/ansible.com.pem
        size: 2048
        # return_content: true
      # register: private_key
      # no_log: true

    - name: Generate CSR
      community.crypto.openssl_csr:
        path: /tmp/ansible.com.csr
        privatekey_path: /tmp/ansible.com.pem
        country_name: "US"
        state_or_province_name: "FL"
        locality_name: "Jax"
        organization_name: "EvOrigin"
        organizational_unit_name: "Lab"
        common_name: "{{ ServerName }}.evorigin.com"
        key_usage:
          - digitalSignature
          - nonRepudiation
          - keyEncipherment
          - dataEncipherment
        extended_key_usage:
          - serverAuth
          - clientAuth
          - codeSigning
          - emailProtection
        subject_alt_name:
          - "DNS:{{ ServerName }}.evorigin.com"
          # Add more SANs as needed, based on the [alt_names] section
        create_key: false
        return_content: true
      register: csr
# - name: "Job Setup"
#   hosts: localhost
#   connection: local
#   gather_facts: no
#   tasks:
#     - name: Obtain iDrac Credential
#       include_role:
#         name: GetVaultCreds
#       vars:
#         includecred:
#           - idrac