---
- name: Generate Private Key and CSR
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Generate Private Key
      community.crypto.openssl_privatekey:
        path: "/tmp/{{ ServerName }}.pem"
        size: 2048
        # return_content: true
      # register: private_key
      # no_log: true

    - name: Generate CSR
      community.crypto.openssl_csr:
        path: "/tmp/{{ ServerName }}.csr"
        privatekey_path: "/tmp/{{ ServerName }}.pem"
        country_name: "US"
        state_or_province_name: "FL"
        locality_name: "Jax"
        organization_name: "EvOrigin"
        organizational_unit_name: "Lab"
        email_address: "admin@lab.local"
        common_name: "{{ ServerName }}.evorigin.com"
        key_usage:
          - digitalSignature
          - nonRepudiation
          - keyEncipherment
          - dataEncipherment
        extended_key_usage:
          - serverAuth
          - clientAuth
          - codeSigning
          - emailProtection
        subject_alt_name:
          - "DNS:{{ ServerName }}.evorigin.com"
          # Add more SANs as needed, based on the [alt_names] section
        # return_content: true
      register: csr

- name: Create Certificate Using MS CA
  hosts: jax-cert001.evorigin.com
  gather_facts: yes
  tasks:
    - name: Create a folder on Windows Server
      win_file:
        path: C:\CertStuff
        state: "{{ ServerName }}"
  
    - name: Copy CSR to CA Server
      copy:
        src: "/tmp/{{ ServerName }}.csr"
        dest: "C:/CertStuff/{{ ServerName }}/{{ ServerName }}.csr"
# - name: "Job Setup"
#   hosts: localhost
#   connection: local
#   gather_facts: no
#   tasks:
#     - name: Obtain iDrac Credential
#       include_role:
#         name: GetVaultCreds
#       vars:
#         includecred:
#           - idrac