---
- name: Run
  hosts: jax-cert001.evorigin.com
  gather_facts: no
  vars:
    pfx_password: "DeleteMe" #This is not really used but it is required by the CA
    ca_config: "jax-cert001.evorigin.com\\evorigin-JAX-CERT001-CA"
    cert_template: "WebServer10years"
    cert_folder: "C:\\CertStuff\\{{ ServerName }}"
  tasks:
    - name: Run the Role
      include_role:
        name: CreateMsCaCertificate
