---
- name: Run PowerShell script on Windows servers
  hosts: all
  gather_facts: no
  connection: winrm

  tasks:
    - name: Execute PowerShell script
      win_shell: |
        Import-Module DupreeFunctions
        Import-DfCredentials
        Invoke-DfDracReset -DracToReset All