---
- name: Reset iDRACs
  hosts: all
  gather_facts: no

  tasks:
    - name: Install Module
      shell: ansible-galaxy collection install dellemc.openmanage
      delegate_to: localhost

    - name: Drac Reset
      dellemc.openmanage.idrac_reset:
        idrac_ip: "{{ inventory_hostname }}"
        idrac_user: "{{ ansible_user }}"
        idrac_password: "{{ ansible_password }}"