---
- name: Install Dell Collection
  hosts: localhost
  gather_facts: no

  tasks:
    - name: install pip
      package:
        name: python3-pip
        state: latest
      run_once: true
      # delegate_to: "{{ groups['controller'][0] }}"
      # become: true
      
    - name: install omsdk
      ansible.builtin.pip:
        name: omsdk
      run_once: true
      # delegate_to: "{{ groups['controller'][0] }}"

    - name: Run ansible-galaxy command
      shell: ansible-galaxy collection install dellemc.openmanage

    - name: Install Role?
      shell: ansible-galaxy install dellemc.openmanage.idrac_reset

    # - name: Show Collections
    #   shell: ansible-galaxy collection list
    #   register: Output

    # - name: Display
    #   debug:
    #     msg: "{{ Output }}"  

- name: Reset iDRACs
  hosts: all
  gather_facts: no

  tasks:
  #   - name: Say OK!
  #     debug:
  #       msg: "OK!"

  - name: iDrac Reset
    dellemc.openmanage.idrac_reset:
      idrac_ip: "{{ inventory_hostname }}"
      idrac_user: "{{ ansible_user }}"
      idrac_password: "{{ ansible_password }}"