---
- name: Install Dell Collection
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Run ansible-galaxy command
      shell: ansible-galaxy collection install dellemc.openmanage

    - name: Show Collections
      shell: ansible-galaxy collection list
      register: Output

    - name: Display
      debug:
        msg: "{{ Output }}"  

- name: Reset iDRACs
  hosts: all
  gather_facts: no

  tasks:
    - name: Say OK!
      debug:
        msg: "OK!"

    # - name: iDrac Reset
    #   dellemc.openmanage.idrac_reset:
    #     idrac_ip: "{{ inventory_hostname }}"
    #     idrac_user: "{{ ansible_user }}"
    #     idrac_password: "{{ ansible_password }}"