---
- name: Reset iDRACs
  hosts: all
  gather_facts: no

  tasks:
    - name: Install Dell Collection
      shell: ansible-galaxy collection install dellemc.openmanage
      delegate_to: localhost
      
    - name: Show Collections
      shell: ansible-galaxy collection list
      register: Output
      delegate_to: localhost

    - name: Display
      debug:
        msg: "{{ Output }}"

    # - name: iDrac Reset
    #   dellemc.openmanage.idrac_reset:
    #     idrac_ip: "{{ inventory_hostname }}"
    #     idrac_user: "{{ ansible_user }}"
    #     idrac_password: "{{ ansible_password }}"