---
- name: Reset iDRACs
  hosts: all
  gather_facts: no
  collections:
    - dellemc.openmanage

  tasks:
    - name: iDrac Reset
      dellemc.openmanage.idrac_reset:
        idrac_ip: "{{ inventory_hostname }}"
        idrac_user: "{{ ansible_user }}"
        idrac_password: "{{ ansible_password }}"