---
- name: Obtain netbox api token
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Obtain credentials from vault
      include_role:
        name: GetVaultCreds
      vars:
        includecred:
          - git
          - netbox

- name: Run 
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Run the Role
      include_role:
        name: GitCreateVmBuildFile
      vars:
        ServerName: "{{ item }}"
      loop: "{{ ServerName_List }}"