---
# using a custom EE which includes this collection so commenting out.
# - name: Run ansible-galaxy command install dellemc.openmanage
#   hosts: localhost
#   connection: local
#   gather_facts: yes
#   tasks:
#     - shell: ansible-galaxy collection install dellemc.openmanage:8.7.0

- name: install omsdk
  hosts: localhost
  tasks:
    - ansible.builtin.pip:
        name: omsdk

- name: "Job Setup"
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Obtain iDrac Credential
      include_role:
        name: GetVaultCreds
        
    - name: "Add RHEL Prod HC Vault hosts to inventory"
      add_host:
        name: "{{ item  }}"
        group: idracs
        # ansible_user: "{{ idrac_cred.username }}"
        # ansible_ssh_pass: "{{ idrac_cred.password }}"
        # ansible_port: 22
        # ansible_connection: ssh
      # no_log: true
      loop:
        - rac-esx1.evorigin.com
        - rac-esx2.evorigin.com
        - rac-esx3.evorigin.com

- name: Run idracReset Role
  hosts: idracs
  gather_facts: no
  tasks: 
    - name: Run the Role
      include_role:
        name: idracReset
      # vars:
      #   all_hosts: "{{ ansible_play_hosts_all }}"