---
- name: install omsdk
  hosts: localhost
  tasks:
    - ansible.builtin.pip:
        name: omsdk

- name: "Job Setup"
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Obtain iDrac Credential
      include_role:
        name: GetVaultCreds

- name: iDrac Reset
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - dellemc.openmanage.idrac_reset:
        idrac_ip: "{{ item }}"
        idrac_user: "{{ idrac_cred.username }}"
        idrac_password: "{{ idrac_cred.password }}"
        validate_certs: false
      loop: "{{ iDracs }}"
      vars: 
        iDracs:
          - rac-esx1.evorigin.com
          - rac-esx2.evorigin.com
          - rac-esx3.evorigin.com
