---
- name: install omsdk
  hosts: localhost
  tasks:
    - ansible.builtin.pip:
        name: omsdk

- name: Clear SEL
  hosts: all
  gather_facts: no
  tasks:
    - raw: 'racadm clrsel'

- name: Clear Job Queue
  hosts: all
  connection: local
  gather_facts: no
  tasks:
    - dellemc.openmanage.idrac_lifecycle_controller_jobs:
        idrac_ip: "{{ inventory_hostname }}"
        idrac_user: "{{ ansible_user }}"
        idrac_password: "{{ ansible_password }}"
        validate_certs: false

- name: iDrac Reset
  hosts: all
  connection: local
  gather_facts: no
  tasks:
    - dellemc.openmanage.idrac_reset:
        idrac_ip: "{{ inventory_hostname }}"
        idrac_user: "{{ ansible_user }}"
        idrac_password: "{{ ansible_password }}"
        validate_certs: false
