---
- name: Create list of server names
  hosts: localhost
  connection: local
  gather_facts: no
  tasks: 
    - name: Set Fact
      set_fact:
        ServerName_List: "{{ ServerNames.split(',') }}"

- name: Run 
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Run the Role
      include_role:
        name: NetboxAddVM
      vars:
        ServerName: "{{ item }}"
      loop: "{{ ServerName_List }}"