---
- name: Run ansible-galaxy command
  hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
    - shell: ansible-galaxy collection install netbox.netbox

# - name: Install pynetbox
#   hosts: localhost
#   gather_facts: no
#   tasks:
#     - ansible.builtin.pip:
#         name: pynetbox

- name: Run 
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Run the Role
      include_role:
        name: NetboxObtainIpVm