---
- name: Install pynetbox
  hosts: localhost
  tasks:
    - ansible.builtin.pip:
        name: pynetbox

- name: Run ansible-galaxy command
  hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
    - shell: ansible-galaxy collection install netbox.netbox

- name: Run 
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Run the Role
      include_role:
        name: NetboxObtainIpVm