---
- name: This is a test
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get Cred
      set_fact:
        test_cred: "{{ lookup('community.hashi_vault.hashi_vault','secret=homelabsecrets/data/dell/iDRAC') }}"