---
- name: Testing Creds to Powershell in AWX 
  hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
    - name: Get Creds from Vault
      include_role:
        name: GetVaultCreds
      vars:
        includecred:
          - test
    - name: Run Powershell
      shell: Write-Host "{{ test_cred.username }}"
      args:
        executable: /usr/bin/pwsh