---
- name: Testing Role Import

  tasks:
    - import_role: 
        name: robertdebock.bootstrap

- name: Run PowerShell script on Windows servers
  hosts: all
  gather_facts: no
  connection: winrm

  tasks:
    - name: Execute PowerShell script
      win_shell: Get-Service
      register: Services

    - name: Show info
      debug: 
        msg: "{{ Services }}"