---
- name: This is a test
  hosts: all
  gather_facts: no
  tasks:
    - name: Get Cred
      set_fact:
        test_cred: "{{ lookup('community.hashi_vault.hashi_vault','secret=HomeLabSecrets/data/linuxroot validate_certs=False') }}"
      # no_log: true
      delegate_to: localhost
      connection: local
      run_once: true

    - name: Run a Command
      command: uptime
      user: "{{ test_cred.username }}"
      password: "{{ test_cred.password }}"
      # no_log: true
      register: command_output

    - debug:
        var: command_output