---
- name: Testing Creds to Powershell in AWX 
  hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
    - name: Get Creds from Vault
      include_role:
        name: GetVaultCreds
      vars:
        includecred:
          - test
    - name: Run Powershell
      shell: |
        $Temp = "{{ test_cred }}"
        write-host "The username is $($Temp.username)
        write-host "The password is $($Temp.password)
      args:
        executable: /usr/bin/pwsh