---
- name: This is a test
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get Cred
      debug:
        msg: "{{ lookup('community.hashi_vault.hashi_vault','secret=/homelabsecrets/data/dell/iDRAC validate_certs=False') }}"