---
- name: Testing Role Import
  hosts: localhost
  tasks:
    - name: Get Requirements File From Git
      get_url:
        url: https://github.com/robertdebock/ansible-role-vault/blob/master/requirements.yml
        dest: /tmp/requirements.yml

    - name: Install Requirements
      community.general.ansible_galaxy_install: 
        type: both
        requirements_file: /tmp/requirements.yml

# - name: Run PowerShell script on Windows servers
#   hosts: all
#   gather_facts: no
#   connection: winrm

#   tasks:
#     - name: Execute PowerShell script
#       win_shell: Get-Service
#       register: Services

#     - name: Show info
#       debug: 
#         msg: "{{ Services }}"