---
- name: This is a test
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get Cred
      debug:
        msg: "{{ lookup('community.hashi_vault.hashi_vault','secret=/v1/homelabsecrets/data/dell/iDRAC') }}"