---
- name: Obtain netbox api token
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Obtain netbox api token
      include_role:
        name: GetVaultCreds
      vars:
        includecred:
          - netbox
          - vCenter
- hosts: all
  gather_facts: False
  roles:
    - VmwareBuildVm