---
# tasks file for GetVaultCreds
- name: Get iDrac cred from Vault
  set_fact:
    idrac_cred: "{{ lookup('community.hashi_vault.hashi_vault','secret=HomeLabSecrets/data/dell/iDRAC validate_certs=False') }}"
  no_log: true
  when: "'idrac' in includecred"

- name: Get Netbox cred from Vault
  set_fact:
    netbox_cred: "{{ lookup('community.hashi_vault.hashi_vault','secret=HomeLabSecrets/data/netbox validate_certs=False') }}"
  no_log: true
  when: "'netbox' in includecred"

- name: Get Git cred from Vault
  set_fact:
    git_cred: "{{ lookup('community.hashi_vault.hashi_vault','secret=HomeLabSecrets/data/git validate_certs=False') }}"
  no_log: true
  when: "'git' in includecred"

- name: Get vCenter cred from Vault
  set_fact:
    vcenter_cred: "{{ lookup('community.hashi_vault.hashi_vault','secret=HomeLabSecrets/data/vmware/vcenter validate_certs=False') }}"
  no_log: true
  when: "'vcenter' in includecred"

- name: Get Local Windows Admin cred from Vault
  set_fact:
    windowslocaladmin_cred: "{{ lookup('community.hashi_vault.hashi_vault','secret=HomeLabSecrets/data/windowslocaladmin validate_certs=False') }}"
  no_log: true
  when: "'windowslocaladmin' in includecred"

- name: Get svcDNS evorigin cred from Vault
  set_fact:
    evorigindns_cred: "{{ lookup('community.hashi_vault.hashi_vault','secret=HomeLabSecrets/data/serviceaccounts/evorigin/svcdns validate_certs=False') }}"
  no_log: true
  when: "'evorigindns' in includecred"

- name: Get evorigin DA cred from Vault
  set_fact:
    evoriginda_cred: "{{ lookup('community.hashi_vault.hashi_vault','secret=HomeLabSecrets/data/serviceaccounts/evorigin/da validate_certs=False') }}"
  no_log: true
  when: "'evoriginda' in includecred"

- name: Get linux root cred from Vault
  set_fact:
    linuxroot_cred: "{{ lookup('community.hashi_vault.hashi_vault','secret=HomeLabSecrets/data/linuxroot validate_certs=False') }}"
  no_log: true
  when: "'linuxroot' in includecred"

- name: Get proxmox root cred from Vault
  set_fact:
    proxmoxroot_cred: "{{ lookup('community.hashi_vault.hashi_vault','secret=HomeLabSecrets/data/proxmox/root validate_certs=False') }}"
  no_log: true
  when: "'proxmoxroot' in includecred"

- name: Test Credential
  set_fact:
    test_cred: "{{ lookup('community.hashi_vault.hashi_vault','secret=HomeLabSecrets/data/test validate_certs=False') }}"
  when: "'test' in includecred"
