---
# tasks file for GetVaultCreds
- name: Get iDrac cred from Vault
  set_fact:
    idrac_cred: "{{ lookup('community.hashi_vault.hashi_vault','secret=homelabsecrets/data/dell/iDRAC validate_certs=False') }}"
  # no_log: true
  when: includecred match "idrac"

# - name: Get Netbox cred from Vault
#   set_fact:
#     netbox_cred: "{{ lookup('community.hashi_vault.hashi_vault','secret=homelabsecrets/data/netbox validate_certs=False') }}"
#   # no_log: true
#   when: netbox in includecred

# - name: This should not run
#   debug:
#     msg: "This should not run..."
#   when: none in includecred