---
- name: Run ansible-galaxy command
  hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
    - shell: ansible-galaxy collection install dellemc.openmanage

- name: install omsdk
  hosts: localhost
  tasks:
    - ansible.builtin.pip:
        name: omsdk

- name: Run idracReset Role
  hosts: "{{ item }}"
  gather_facts: no
  tasks: 
    - name: Run the Role
      include_role:
        name: idracReset
      loop: "{{ ansible_play_hosts }}"
      when: item != "localhost"
      delegate_to: localhost