---
- name: Run ansible-galaxy command
  hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
    - shell: ansible-galaxy collection install dellemc.openmanage

- name: install omsdk
  ansible.builtin.pip:
    name: omsdk
  run_once: true

- name: Run idracReset Role
  hosts: all
  gather_facts: yes
  tasks: 
    - name: Run the Role
      include_role:
        name: idracReset
