---
# tasks file for ansibleroledemo/BrocadeZoneServerB

#FindServer.yml
- name: Find Server B Side
  raw: 'portname | grep {{ ServerName }}'
  register: SWBInfo
  ignore_errors: yes
  when: ServerName is defined

#RetrieveWWNs.yml
- name: Get WWN B
  raw: 'portshow {{ PortNumberB }}'
  register: PortInfoB

#CreateAlias.yml
- name: Create An Alias B Side
  raw: 'alicreate {{ AliasBName }},"{{ WWNB }}"'

- name: Save Config
  raw: 'cfgsave -f'

#CreateZone.yml
- name: Create B Side Zone 1
  raw: 'zonecreate {{ ZoneB1Name }},"{{ AliasBName }};{{ Array }}_{{ Port1B }}"'

- name: Create B Side Zone 2
  raw: 'zonecreate {{ ZoneB2Name }},"{{ AliasBName }};{{ Array }}_{{ Port2B }}"'

- name: Save Config
  raw: 'cfgsave -f'

#FindConfigName.yml
- name: Get Config Name B
  raw: 'configshow | grep enable:'
  register: CfgResponseB

#UpdateZoneSet.yml
- name: Update the Config
  raw: 'cfgadd {{ CfgNameB }},"{{ ZoneB1Name }};{{ ZoneB2Name }}"'

- name: Enable Config
  raw: "cfgenable {{ CfgNameB }} -f"