---
# tasks file for DeployVault
- name: configure firewall rules
  ansible.posix.firewalld:
    port: "{{ item }}"
    zone: public
    state: enabled
    permanent: true
  vars:
    ports:
      - 8200/tcp
      - 8201/tcp
  loop: "{{ ports }}"

- name: reload firewalld
  shell: firewall-cmd --reload

- name: Install Config Manager
  ansible.builtin.yum:
    name: yum-utils
    state: present

- name: Add HC LNX Repo
  ansible.builtin.shell: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

- name: Install Vault
  ansible.builtin.yum:
    name: vault-1.15.6
    state: present

- name: Create data folder
  ansible.builtin.file:
    path: /var/lib/vault/data
    state: directory
    owner: vault
    group: vault

- name: Create vault config file
  ansible.builtin.template:
    src: templates/config.hcl.j2
    dest: /etc/vault.d/vault.hcl
    owner: vault
    group: vault

- name: Insert VAULT_ADDR in to /etc/profile
  lineinfile:
    path: /etc/profile
    line: export VAULT_ADDR="https://$(hostname):8200"

- name: Insert VAULT_ADDR in to .bashrc
  lineinfile:
    path: /etc/bashrc
    line: export VAULT_ADDR="https://$(hostname):8200"

- name: Start Vault Service
  ansible.builtin.service:
    name: vault
    state: restarted
    enabled: true
