---
# tasks file for AwxAddHostToInventory
- name: Get VM Info
  include_role:
    name: GitGetVmInfo
  vars:
    ServerName: "{{ ServerName }}"
  when: VmFileContents_JSON is not defined
  
- name: ServerName to Upper
  set_fact: ServerNameUpper="{{ ServerName | upper }}"

- name: Add AlmaLinux Server to AWX Inventory
  awx.awx.host:
    name: "{{ ServerNameUpper }}"
    inventory: "Linux"
    controller_host: "jax-k3s001.evorigin.com"
    state: present
  when: '"Alma" in VmFileContents_JSON.VMInfo.OperatingSystem'

- name: Add AlmaLinux Server to AlmaLinux Group
  awx.awx.group:
    name: "AlmaLinux"
    inventory: "Linux"
    hosts:
      - "{{ ServerNameUpper }}"
    state: present
  when: '"Alma" in VmFileContents_JSON.VMInfo.OperatingSystem'