#Inputs Required:
#  ServerName
---
- hosts: 10.92.238.99
  vars:
    ServerInfoA: "{{ SWAInfo.stdout }}"
    SplitA1: "{{ ServerInfoA.split() }}"
    PortNumberA: "{{ SplitA1[1].replace(':', '') }}"
    SplitA2: "{{ SplitA1[2].split('_') }}"
    AliasAName: "{{ SplitA2[1] + '_' + SplitA2[2] }}"
  gather_facts: False
  tasks:
    - name: Find Server A Side
      raw: 'portname | grep {{ ServerName }}'
      register: SWAInfo
      ignore_errors: yes
      when: ServerName is defined

    - name: Get Side A Alias Name
      debug:
        msg: "{{ AliasAName }} {{ PortNumberA }}"
      when: SWAInfo.rc == 0

- hosts: 10.92.238.100
  vars:
    ServerInfoB: "{{ SWBInfo.stdout }}"
    SplitB1: "{{ ServerInfoB.split() }}"
    PortNumberB: "{{ SplitB1[1].replace(':', '') }}"
    SplitB2: "{{ SplitB1[2].split('_') }}"
    AliasBName: "{{ SplitB2[1] + '_' + SplitB2[2] }}"
  gather_facts: False
  tasks:
    - name: Find Server B Side
      raw: 'portname | grep {{ ServerName }}'
      register: SWBInfo
      ignore_errors: yes
      when: ServerName is defined

    - name: Get Side B Alias Name
      debug:
        msg: "{{ AliasBName }} {{ PortNumberB }}"
      when: SWBInfo.rc == 0