---
# tasks file for GitGetVmInfo
# - name: Show me the contents inside GitGetVmInfo
#   debug:
#     var: ServerName

- name: Get raw JSON file from github
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/compengevfan/vmbuildfiles/refs/heads/main/v2/{{ ServerName }}.json"
    dest: "/tmp/{{ ServerName }}.json"

- name: Obtain contents of downloaded file and convert to JSON
  set_fact:
    FileContents_JSON: "{{ lookup('file', '/tmp/{{ ServerName }}.json') | from_json }}"
