---
# tasks file for NetboxAddVM
- name: Make sure ServerName is all upper
  set_fact: ServerNameUpper="{{ ServerName | upper }}"

- name: Get VM Info
  include_role:
    name: GitGetVmInfo
  vars:
    ServerName: "{{ ServerName }}"

- name: Create VM
  netbox.netbox.netbox_virtual_machine:
    netbox_url: "{{ netbox_cred.url }}"
    netbox_token: "{{ netbox_cred.token }}"
    data:
      name: "{{ ServerNameUpper }}"
      site: Amberly
      vcpus: "{{ FileContents_JSON.VMInfo.vCPUs | int }}"
      memory: "{{ FileContents_JSON.VMInfo.RAM | int * 1024 }}"
      platform: "{{ FileContents_JSON.VMInfo.OperatingSystem }}"
      cluster: C1
      custom_fields:
        Datastore: "{{ FileContents_JSON.VMInfo.Datastore }}"
        vCenterFolderPath: "{{ FileContents_JSON.VMInfo.vCenterFolderPath }}"
        OU: "{{ FileContents_JSON.VMInfo.OU }}"
    state: present
    validate_certs: no
  register: VirtualMachine

- name: What am I getting?
  debug:
    msg: "{{ VirtualMachine | to_json }}"

- name: Create the interface and IP if it doesn't exist
  block: 
    - name: Create interface
      netbox.netbox.netbox_vm_interface:
        netbox_url: "{{ netbox_cred.url }}"
        netbox_token: "{{ netbox_cred.token }}"
        data:
          virtual_machine: "{{ ServerNameUpper }}"
          name: eth1
          enabled: true
        state: present
        validate_certs: no

    - name: Convert subnet name to prefix
      set_fact:
        subnetPrefixMap:
          JAX-EvOrigin: "192.168.0.0/23"
          Test: "10.10.10.0/24"

    - name: Select correct prefix
      set_fact:
        selectedPrefix: "{{ subnetPrefixMap.get(FileContents_JSON.VMInfo.Network) }}"

    - name: Find the prefix
      ansible.builtin.uri:
        url: "{{ netbox_cred.url }}/api/ipam/prefixes?prefix={{ selectedPrefix }}"
        headers:
          Content-Type: application/json
          Authorization: "{{ netbox_cred.api_token }}"
        validate_certs: no
      register: prefix

    - name: Get the available IPs in the prefix
      ansible.builtin.uri:
        url: "{{ netbox_cred.url }}/api/ipam/prefixes/{{ prefix.json.results[0].id }}/available-ips/"
        headers:
          Content-Type: application/json
          Authorization: "{{ netbox_cred.api_token }}"
        validate_certs: no
      register: availableIps

    - name: Create an IP address
      netbox.netbox.netbox_ip_address:
        netbox_url: "{{ netbox_cred.url }}"
        netbox_token: "{{ netbox_cred.token }}"
        data:
          address: "{{ availableIps.json[0].address }}"
          dns_name: "{{ ServerNameUpper }}.evorigin.com"
          assigned_object: 
            name: eth1
            virtual_machine: "{{ ServerNameUpper }}"
        state: present
        validate_certs: no

    - name: Set IP as primary
      netbox.netbox.netbox_virtual_machine:
        netbox_url: "{{ netbox_cred.url }}"
        netbox_token: "{{ netbox_cred.token }}"
        data:
          name: "{{ ServerNameUpper }}"
          site: Amberly
          cluster: C1
          primary_ip4: "{{ availableIps.json[0].address.split('/')[0] }}"
        state: present
        validate_certs: no

    # - name: Call the role to add IP to DNS
  when: VirtualMachine.virtual_machine.primary_ip is not defined
