---
# tasks file for NetboxAddVM
- name: Obtain netbox api token
  include_role:
    name: GetVaultCreds
  vars:
    includecred:
      - netbox

- name: Create VM
  netbox.netbox.netbox_virtual_machine:
    netbox_url: "{{ netbox_cred.url }}"
    netbox_token: "{{ netbox_cred.token }}"
    data:
      name: Create-Test-VM
      site: Amberly
      cluster: C1
    state: present
    validate_certs: no

# - name: Get IP address
#   netbox.netbox.netbox_ip_address:
#     netbox_url: "{{ netbox_cred.url }}"
#     netbox_token: "{{ netbox_cred.token }}"
#     data:
#       address: 10.10.10.1
#     state: present
#     validate_certs: no
#   register: IpOutput

# - name: Show Info
#   debug:
#     msg: "{{ IpOutput }}"
