---
# tasks file for NetboxAddVM
- name: Obtain netbox api token
  include_role:
    name: GetVaultCreds
  vars:
    includecred:
      - netbox

- name: Create VM
  netbox.netbox.netbox_virtual_machine:
    netbox_url: "{{ netbox_cred.url }}"
    netbox_token: "{{ netbox_cred.token }}"
    data:
      name: Create-Test-VM
      site: Amberly
      cluster: C1
    state: present
    validate_certs: no

- name: Create interface
  netbox.netbox.netbox_vm_interface:
    netbox_url: "{{ netbox_cred.url }}"
    netbox_token: "{{ netbox_cred.token }}"
    data:
      virtual_machine: Create-Test-VM
      name: eth1
      enabled: true
    state: present
    validate_certs: no

- name: Create an IP address
  netbox.netbox.netbox_ip_address:
    netbox_url: "{{ netbox_cred.url }}"
    netbox_token: "{{ netbox_cred.token }}"
    data:
      address: 10.10.10.2/24
      dns_name: Create-Test-VM.evorigin.com
      assigned_object: 
        name: eth1
        virtual_machine: Create-Test-VM
    state: present
    validate_certs: no
