---
# tasks file for NetboxAddVM
- name: Create VM
  netbox.netbox.netbox_virtual_machine:
    netbox_url: "{{ netbox_cred.url }}"
    netbox_token: "{{ netbox_cred.token }}"
    data:
      name: "{{ ServerName }}"
      site: Amberly
      vcpus: "{{ vCPUs | int }}"
      memory: "{{ RAM | int }}"
      platform: "{{ OperatingSystem }}"
      cluster: C1
      custom_fields:
        Datastore: "{{ Datastore }}"
    state: present
    validate_certs: no

- name: Create interface
  netbox.netbox.netbox_vm_interface:
    netbox_url: "{{ netbox_cred.url }}"
    netbox_token: "{{ netbox_cred.token }}"
    data:
      virtual_machine: "{{ ServerName }}"
      name: eth1
      enabled: true
    state: present
    validate_certs: no

- name: Convert subnet name to prefix
  set_fact:
    subnetPrefixMap:
      JAX-EvOrigin: "192.168.0.0/23"
      Test: "10.10.10.0/24"

- name: Select correct prefix
  set_fact:
    selectedPrefix: "{{ subnetPrefixMap.get(Network) }}"

# - name: What am I getting?
#   debug:
#     msg: "The contents of the selectedPrefix variable are {{ selectedPrefix }}"

- name: Find the prefix
  ansible.builtin.uri:
    url: "{{ netbox_cred.url }}/api/ipam/prefixes?prefix={{ selectedPrefix }}"
    headers:
      Content-Type: application/json
      Authorization: "{{ netbox_cred.api_token }}"
    validate_certs: no
  register: prefix

- name: Get the available IPs in the prefix
  ansible.builtin.uri:
    url: "{{ netbox_cred.url }}/api/ipam/prefixes/{{ prefix.json.results[0].id }}/available-ips/"
    headers:
      Content-Type: application/json
      Authorization: "{{ netbox_cred.api_token }}"
    validate_certs: no
  register: availableIps

- name: Show me the address?
  debug:
    msg: "{{ availableIps.json[0].address }}"

- name: Create an IP address
  netbox.netbox.netbox_ip_address:
    netbox_url: "{{ netbox_cred.url }}"
    netbox_token: "{{ netbox_cred.token }}"
    data:
      address: "{{ availableIps.json[0].address }}"
      dns_name: "{{ ServerName }}.evorigin.com"
      assigned_object: 
        name: eth1
        virtual_machine: "{{ ServerName }}"
    state: present
    validate_certs: no
  # ignore_errors: true

# - name: Create an IP address
#   netbox.netbox.netbox_ip_address:
#     netbox_url: "{{ netbox_cred.url }}"
#     netbox_token: "{{ netbox_cred.token }}"
#     data:
#       address: "{{ FileContents_JSON.VMInfo.IPAddress }}{{FileContents_JSON.VMInfo.Subnet}}"
#       dns_name: "{{ ServerName }}.evorigin.com"
#       assigned_object: 
#         name: eth1
#         virtual_machine: "{{ ServerName }}"
#     state: present
#     validate_certs: no
#   # ignore_errors: true

- name: Set IP as primary
  netbox.netbox.netbox_virtual_machine:
    netbox_url: "{{ netbox_cred.url }}"
    netbox_token: "{{ netbox_cred.token }}"
    data:
      name: "{{ ServerName }}"
      site: Amberly
      cluster: "{{ FileContents_JSON.VMInfo.Cluster }}"
      primary_ip4: "{{ FileContents_JSON.VMInfo.IPAddress }}"
    state: present
    validate_certs: no