---
# tasks file for NetboxAddVM
- name: Get VM Info
  include_role:
    name: GetVmInfo
  vars:
    ServerName: "{{ ServerName }}"

- name: Obtain netbox api token
  include_role:
    name: GetVaultCreds
  vars:
    includecred:
      - netbox

- name: Create VM
  netbox.netbox.netbox_virtual_machine:
    netbox_url: "{{ netbox_cred.url }}"
    netbox_token: "{{ netbox_cred.token }}"
    data:
      name: "{{ ServerName }}"
      site: Amberly
      cluster: C1
    state: present
    validate_certs: no

- name: Create interface
  netbox.netbox.netbox_vm_interface:
    netbox_url: "{{ netbox_cred.url }}"
    netbox_token: "{{ netbox_cred.token }}"
    data:
      virtual_machine: "{{ ServerName }}"
      name: eth1
      enabled: true
    state: present
    validate_certs: no

- name: Create an IP address
  netbox.netbox.netbox_ip_address:
    netbox_url: "{{ netbox_cred.url }}"
    netbox_token: "{{ netbox_cred.token }}"
    data:
      address: "{{ FileContents_JSON.VMInfo.IPAddress }}/24"
      dns_name: "{{ ServerName }}.evorigin.com"
      assigned_object: 
        name: eth1
        virtual_machine: "{{ ServerName }}"
    state: present
    validate_certs: no

- name: Set IP as primary
  netbox.netbox.netbox_virtual_machine:
    netbox_url: "{{ netbox_cred.url }}"
    netbox_token: "{{ netbox_cred.token }}"
    data:
      name: "{{ ServerName }}"
      site: Amberly
      cluster: C1
      primary_ip4: "{{ FileContents_JSON.VMInfo.IPAddress }}"
    state: present
    validate_certs: no