---
# tasks file for ansibleroledemo/BrocadeDecomServerB

#FindConfigName.yml
- name: Get Config Name B
  raw: 'configshow | grep enable:'
  register: CfgResponseB

#RemoveZoneSet.yml
- name: Get Zone Names B Side
  raw: 'zoneshow --ic "z_{{ ServerName }}*" | grep zone'
  register: ZoneResponseB

- name: Remove Zones from ZoneSet B Side
  raw: 'cfgremove {{ CfgNameB }}, "{{ ZoneB1Name }};{{ ZoneB2Name }}"'

- name: Enable Config
  raw: "cfgenable {{ CfgNameB }} -f"

#RemoveZone.yml
- name: Remove Zone 1 B Side
  raw: "zonedelete {{ ZoneB1Name }}"

- name: Remove Zone 2 B Side
  raw: "zonedelete {{ ZoneB2Name }}"

- name: Save Config
  raw: 'cfgsave -f'

#RemoveAlias.yml
- name: Find Server Alias Name
  raw: "alishow | grep 'alias:[[:space:]]{{ ServerName }}'"
  register: AliasResponseB

- name: Remove Alias on B Side
  raw: "alidelete {{ AliasB }}"

- name: Save Config
  raw: 'cfgsave -f'