---
# tasks file for ansibleroledemo/BrocadeZoneServerA

#FindServer.yml
- name: Find Server A Side
  raw: 'portname | grep {{ ServerName }}'
  register: SWAInfo
  ignore_errors: yes
  when: ServerName is defined

#RetrieveWWNs.yml
- name: Get WWN A
  raw: 'portshow {{ PortNumberA }}'
  register: PortInfoA

#CreateAlias.yml
- name: Create An Alias A Side
  raw: 'alicreate {{ AliasAName }},"{{ WWNA }}"'

- name: Save Config
  raw: 'cfgsave -f'

#CreateZone.yml
- name: Create A Side Zone 1
  raw: 'zonecreate {{ ZoneA1Name }},"{{ AliasAName }};{{ Array }}_{{ Port1A }}"'

- name: Create A Side Zone 2
  raw: 'zonecreate {{ ZoneA2Name }},"{{ AliasAName }};{{ Array }}_{{ Port2A }}"'

- name: Save Config
  raw: 'cfgsave -f'

#FindConfigName.yml
- name: Get Config Name A
  raw: 'configshow | grep enable:'
  register: CfgResponseA

#UpdateZoneSet.yml
- name: Update the Config
  raw: 'cfgadd {{ CfgNameA }},"{{ ZoneA1Name }};{{ ZoneA2Name }}"'

- name: Enable Config
  raw: "cfgenable {{ CfgNameA }} -f"