#Inputs Required:
#  AliasAName, AliasBName, WWNA, WWNB
---
- hosts: 10.92.238.99
  gather_facts: False
  tasks:
    - name: Create An Alias A Side
      raw: 'alicreate {{ AliasAName }},"{{ WWNA }}"'

    - name: Save Config
      raw: 'cfgsave -f'

- hosts: 10.92.238.100
  gather_facts: False
  tasks:
    - name: Create An Alias B Side
      raw: 'alicreate {{ AliasBName }},"{{ WWNB }}"'

    - name: Save Config
      raw: 'cfgsave -f'