---
# tasks file for ansibleroledemo/BrocadeDecomServerA

#FindConfigName.yml
- name: Get Config Name A
  raw: 'configshow | grep enable:'
  register: CfgResponseA

#RemoveZoneSet.yml
- name: Get Zone Names A Side
  raw: 'zoneshow --ic "z_{{ ServerName }}*" | grep zone'
  register: ZoneResponseA

- name: Remove Zones from ZoneSet A Side
  raw: 'cfgremove {{ CfgNameA }}, "{{ ZoneA1Name }};{{ ZoneA2Name }}"'

- name: Enable Config
  raw: "cfgenable {{ CfgNameA }} -f"

#RemoveZone.yml
- name: Remove Zone 1 A Side
  raw: "zonedelete {{ ZoneA1Name }}"

- name: Remove Zone 2 A Side
  raw: "zonedelete {{ ZoneA2Name }}"

- name: Save Config
  raw: 'cfgsave -f'

#RemoveAlias.yml
- name: Find Server Alias Name
  raw: "alishow | grep 'alias:[[:space:]]{{ ServerName }}'"
  register: AliasResponseA

- name: Remove Alias on A Side
  raw: "alidelete {{ AliasA }}"

- name: Save Config
  raw: 'cfgsave -f'