---
# tasks file for idracReset
- name: iDrac Reset
  dellemc.openmanage.idrac_reset:
    idrac_ip: "{{ ansible_host }}"
    idrac_user: "{{ ansible_user }}"
    idrac_password: "{{ ansible_password }}"
    validate_certs: false
  # loop: "{{ ansible_play_hosts }}"
  # when: item != "localhost"
  # delegate_to: localhost