---
# tasks file for DeployVault
- name: Install unzip if needed
  ansible.builtin.yum:
    name: unzip
    state: present

#Figure out how to not run this every time...
- name: Download and extract vault
  ansible.builtin.unarchive:
    src: https://hashicorp-releases.yandexcloud.net/vault/1.15.5/vault_1.15.5_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: true

- name: Create config directory Vault
  ansible.builtin.file:
    path: "/etc/vault"
    state: directory

- name: Create Vault Data Folder
  ansible.builtin.file:
    path: "/var/lib/vault/data"
    state: directory

- name: Copy vault config file from template 
  ansible.builtin.template:
    src: templates/config.hcl.j2
    dest: "/etc/vault/config.hcl"

- name: Copy vault systemd service file from template
  ansible.builtin.template:
    src: templates/vault.service.j2
    dest: /etc/systemd/system/vault.service
  notify:
    - vault_restart

- name: Test Command
  shell: systemctl status firewalld

- name: Say OK!
  debug:
    msg: "OK!"