---
# tasks file for DeployVault
- name: Clone the ansible-role-vault repo
  git: 
    repo: 'https://github.com/robertdebock/ansible-role-vault.git'
    dest: /tmp/ansible-role-vault
    version: master
  delegate_to: localhost

- name: Install Requirements
  shell: ansible-galaxy install --role-file /tmp/ansible-role-vault/requirements.yml
  delegate_to: localhost

- name: Install Vault Role
  shell: ansible-galaxy install robertdebock.vault
  delegate_to: localhost

- name: install vault?
  roles:
    - robertdebock.bootstrap
    - robertdebock.core_dependencies
    - robertdebock.hashicorp
    - robertdebock.vault
  

- name: Say OK!
  debug:
    msg: "OK!"