---
# tasks file for DeployVault
- name: Clone the ansible-role-vault repo
  git: 
    repo: 'https://github.com/robertdebock/ansible-role-vault.git'
    dest: /tmp/ansible-role-vault
    version: master

- name: Install Requirements
  shell: ansible-galaxy install --role-file /tmp/ansible-role-vault/requirements.yml

- name: Say OK!
  debug:
    msg: "OK!"