---
# tasks file for DeployVault
- name: Download and extract vault
  ansible.builtin.unarchive:
    src: https://hashicorp-releases.yandexcloud.net/vault/1.15.5/vault_1.15.5_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: true

- name: Create config directory Vault
  ansible.builtin.file:
    path: "/etc/vault"
    state: directory

- name: Create Vault Data Folder
  ansible.builtin.file:
    path: "/var/lib/vault/data"
    state: directory

- name: Copy vault config file from template 
  ansible.builtin.template:
    src: templates/config.hcl
    dest: "/etc/vault/config.hcl"

- name: Test Command
  shell: systemctl status firewalld

- name: Say OK!
  debug:
    msg: "OK!"