---
# tasks file for NetboxObtainIP
- name: Test Connectivity with Ping
  shell: ping jax-nbx001.evorigin.com -c 3

- name: install NC
  shell: sudo yum install netcat -y

- name: Test Connectivity with nc
  shell: nc -zv 192.168.1.140 443

- name: Obtain netbox api token
  include_role:
    name: GetVaultCreds
  vars:
    includecred:
      - netbox

- name: Get IP address
  netbox.netbox.netbox_ip_address:
    netbox_url: https://jax-nbx001.evorigin.com
    netbox_token: "{{ netbox_cred.token }}"
    data:
      address: 10.10.10.1
    state: present
    validate_certs: no
  register: IpOutput

- name: Show Info
  debug:
    msg: "{{ IpOutput }}"
