---
# tasks file for NetboxObtainIP
- name: Get IP address
  netbox.netbox.netbox_ip_address:
    netbox_url: https://jax-nbx001.evorigin.com
    netbox_token: "{{ ansible_password }}"
    data:
      address: 10.10.10.1
      tenant: TestTenant1
    state: present
    validate_certs: no
  register: IpOutput

- name: Show Info
  debug:
    msg: "{{ IpOutput }}"

- name: Create IP in TestTenant1
  netbox.netbox.netbox_ip_address:
    netbox_url: https://jax-nbx001.evorigin.com
    netbox_token: "{{ ansible_password }}"
    data:
      prefix: 10.10.10.0/23
      tenant: TestTenant1
    state: new

- name: Create IP in TestTenant2
  netbox.netbox.netbox_ip_address:
    netbox_url: https://jax-nbx001.evorigin.com
    netbox_token: "{{ ansible_password }}"
    data:
      prefix: 10.10.10.0/23
      tenant: TestTenant2
    state: new