---
# tasks file for NetboxObtainIP
- name: WTF am I running?
  shell: hostnamectl

# - name: install NC
#   shell: dnf install netcat -y

# - name: Test Connectivity with nc
#   shell: nc -zv 192.168.1.140 443

# - name: Obtain netbox api token
#   include_role:
#     name: GetVaultCreds
#   vars:
#     includecred:
#       - netbox

# - name: Get IP address
#   netbox.netbox.netbox_ip_address:
#     netbox_url: https://jax-nbx001.evorigin.com
#     netbox_token: "{{ netbox_cred.token }}"
#     data:
#       address: 10.10.10.1
#     state: present
#     validate_certs: no
#   register: IpOutput

# - name: Show Info
#   debug:
#     msg: "{{ IpOutput }}"
