---
# tasks file for BuildVM
- name: Obtain Credentials
  include_role:
    name: GetVaultCreds
  vars:
    includecred:
      - netbox
      - vcenter

# - name: Show me the contents
#   debug:
#     msg: "{{ netbox_cred }}"

# - name: Get VM Info from Netbox
#   netbox.netbox.netbox_virtual_machine:
#     netbox_url: "{{ netbox_cred.url }}"
#     netbox_token: "{{ netbox_cred.token }}"
#     data:
#       name: "{{ ServerName }}"
#     state: present
#     validate_certs: no

- name: Get VM Info from Netbox API
  ansible.builtin.uri:
    url: "{{ netbox_cred.url }}/api/virtualization/virtual-machines/"
    headers:
      Content-Type: application/json
      Authorization: "Token {{ netbox_cred.token }}"
    validate_certs: no