---
# tasks file for CreateDnsARecord
- name: Obtain evorigin.com svcDNS service account cred
  include_role:
    name: GetVaultCreds
  vars:
    includecred:
      - evorigindns

- name: What am I getting (ServerNameUpper)?
  debug:
    var: ServerNameUpper

- name: What am I getting (IpAddress)?
  debug:
    var: IpAddress

- name: What am I getting (Domain)?
  debug:
    var: Domain

- name: What am I getting (Cred)?
  debug:
    var: evorigindns_cred