---
# tasks file for CreateDnsARecord
- name: What am I getting (DnsServerName)?
  debug:
    var: DnsServerName

- name: What am I getting (IpAddress)?
  debug:
    var: IpAddress

- name: What am I getting (Domain)?
  debug:
    var: Domain