---
# tasks file for CreateDnsARecord
- name: What am I getting (ServerNameUpper)?
  debug:
    var: ServerNameUpper

- name: What am I getting (IpAddress)?
  debug:
    var: IpAddress

- name: What am I getting (Domain)?
  debug:
    var: Domain